```{r}
setwd('d:/Columbia/AA/framework2/project')
azdias_clean = read.csv('azdias_clean.csv')
```
```{r}
#use PCA
library(FactoMineR)
pca_facto = PCA(azdias_clean,scale.unit = T,graph =F)
```
```{r}
#visulization of cumulative_variance
cumulative_variance = data.frame(pc=c(1:125),cumulative_variance_explained=pca_facto$eig[,3]);
ggplot(cumulative_variance,aes(x=pc,y=cumulative_variance_explained))+
  geom_line()
```
```{r}
#visualization
library(factoextra)
fviz_eig(pca_facto,ncp=125,addlabels = T)
```
```{r}
#check variance explained, and I select 77 pc
pca_facto$eig
```
```{r}
#run with 77 pc
pca_facto = PCA(azdias1_impute,scale.unit = T,ncp = 77,graph = F)
```
```{r}
#print result
print(pca_facto)
```
```{r}
#check weights for variables
var <- get_pca_var(pca_facto)
var
sort(var$cor[,1]) ## weights for variables, pc1,  
#FINANZ_MINIMALIST, most negtive corelated,
#LP_STATUS_GROB_1, most positive corelated
```
```{r}
sort(var$cor[,2])
#ALTERSKATEGORIE_GROB, most negtive corelated,
#SEMIO_REL, most positive corelated
```
```{r}
sort(var$cor[,3])
#SEMIO_VERT, most negtive corelated,
#ANREDE_KZ, most positive corelated
```
```{r}
#use pca coordinates for the original data
pca_df = as.data.frame(pca_facto$ind$coord)
pca_df = round(pca_df,2)
```

```{r}
#visulization
fviz_pca_var(pca_facto, axes = c(1,1), col.var = "contrib", 
  select.var = list(contrib = 5), gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),col.circle = 'steelblue',repel = T)
```
```{r}
fviz_pca_var(pca_facto, axes = c(2,2), col.var = "contrib", 
  select.var = list(contrib = 5), gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),col.circle = 'steelblue',repel = T)
```


```{r}
# kmeans, choose number of clusters
set.seed(1706)
km_cluster_1 = kmeans(x = pca_df,centers = 1,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_2 = kmeans(x = pca_df,centers = 2,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_3 = kmeans(x = pca_df,centers = 3,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_4 = kmeans(x = pca_df,centers = 4,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_5 = kmeans(x = pca_df,centers = 5,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_6 = kmeans(x = pca_df,centers = 6,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_7 = kmeans(x = pca_df,centers = 7,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_8 = kmeans(x = pca_df,centers = 8,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_9 = kmeans(x = pca_df,centers = 9,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_10 = kmeans(x = pca_df,centers = 10,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_11 = kmeans(x = pca_df,centers = 11,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_12 = kmeans(x = pca_df,centers = 12,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_13 = kmeans(x = pca_df,centers = 13,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_14 = kmeans(x = pca_df,centers = 14,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_15 = kmeans(x = pca_df,centers = 15,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_16 = kmeans(x = pca_df,centers = 16,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_17 = kmeans(x = pca_df,centers = 17,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_18 = kmeans(x = pca_df,centers = 18,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_19 = kmeans(x = pca_df,centers = 19,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_20 = kmeans(x = pca_df,centers = 20,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_21 = kmeans(x = pca_df,centers = 21,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_22 = kmeans(x = pca_df,centers = 22,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_23 = kmeans(x = pca_df,centers = 23,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_24 = kmeans(x = pca_df,centers = 24,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_25 = kmeans(x = pca_df,centers = 25,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_26 = kmeans(x = pca_df,centers = 26,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_27 = kmeans(x = pca_df,centers = 27,iter.max = 1000,nstart = 25)
set.seed(1706)
km_cluster_28 = kmeans(x = pca_df,centers = 28,iter.max = 1000,nstart = 25)
```
```{r}
```
```{r}
ratio_ss_1 = km_cluster_1$betweenss/km_cluster_1$totss;ratio_ss_1
ratio_ss_2 = km_cluster_2$betweenss/km_cluster_2$totss;ratio_ss_2
ratio_ss_3 = km_cluster_3$betweenss/km_cluster_3$totss;ratio_ss_3
ratio_ss_4 = km_cluster_4$betweenss/km_cluster_4$totss;ratio_ss_4
ratio_ss_5 = km_cluster_5$betweenss/km_cluster_5$totss;ratio_ss_5
ratio_ss_6 = km_cluster_6$betweenss/km_cluster_6$totss;ratio_ss_6
ratio_ss_7 = km_cluster_7$betweenss/km_cluster_7$totss;ratio_ss_7
ratio_ss_8 = km_cluster_8$betweenss/km_cluster_8$totss;ratio_ss_8
ratio_ss_9 = km_cluster_9$betweenss/km_cluster_9$totss;ratio_ss_9
ratio_ss_10 = km_cluster_10$betweenss/km_cluster_10$totss;ratio_ss_10
ratio_ss_11 = km_cluster_11$betweenss/km_cluster_11$totss;ratio_ss_11
ratio_ss_12 = km_cluster_12$betweenss/km_cluster_12$totss;ratio_ss_12
ratio_ss_13 = km_cluster_13$betweenss/km_cluster_13$totss;ratio_ss_13
ratio_ss_14 = km_cluster_14$betweenss/km_cluster_14$totss;ratio_ss_14
ratio_ss_15 = km_cluster_15$betweenss/km_cluster_15$totss;ratio_ss_15
ratio_ss_16 = km_cluster_16$betweenss/km_cluster_16$totss;ratio_ss_16
ratio_ss_17 = km_cluster_17$betweenss/km_cluster_17$totss;ratio_ss_17
ratio_ss_18 = km_cluster_18$betweenss/km_cluster_18$totss;ratio_ss_18
ratio_ss_19 = km_cluster_19$betweenss/km_cluster_19$totss;ratio_ss_19
ratio_ss_20 = km_cluster_20$betweenss/km_cluster_20$totss;ratio_ss_20
ratio_ss_21 = km_cluster_21$betweenss/km_cluster_21$totss;ratio_ss_21
ratio_ss_22 = km_cluster_22$betweenss/km_cluster_22$totss;ratio_ss_22
ratio_ss_23 = km_cluster_23$betweenss/km_cluster_23$totss;ratio_ss_23
ratio_ss_24 = km_cluster_24$betweenss/km_cluster_24$totss;ratio_ss_24
ratio_ss_25 = km_cluster_25$betweenss/km_cluster_25$totss;ratio_ss_25
ratio_ss_26 = km_cluster_26$betweenss/km_cluster_26$totss;ratio_ss_26
ratio_ss_27 = km_cluster_27$betweenss/km_cluster_27$totss;ratio_ss_27
ratio_ss_28 = km_cluster_28$betweenss/km_cluster_28$totss;ratio_ss_28



ratio_ss = c(ratio_ss_1,ratio_ss_2,ratio_ss_3,ratio_ss_4,ratio_ss_5,ratio_ss_6,ratio_ss_7,ratio_ss_8,ratio_ss_9,ratio_ss_10,ratio_ss_11,ratio_ss_12,ratio_ss_13,ratio_ss_14,ratio_ss_15,ratio_ss_16,ratio_ss_17,ratio_ss_18,ratio_ss_19,ratio_ss_20,ratio_ss_21,ratio_ss_22,ratio_ss_23,ratio_ss_24,ratio_ss_25,ratio_ss_26,ratio_ss_27,ratio_ss_28)
ratio_ss
library(ggplot2)
ggplot(data=data.frame(cluster = 1:28,ratio_ss),aes(x=cluster,y=ratio_ss))+
  geom_line(col='steelblue',size=1.2)+
  geom_point()+
  scale_x_continuous(breaks=seq(1,28,1))
```
```{r}
within_ss_1 = km_cluster_1$tot.withinss;within_ss_1
within_ss_2 = km_cluster_2$tot.withinss;within_ss_2
within_ss_3 = km_cluster_3$tot.withinss;within_ss_3
within_ss_4 = km_cluster_4$tot.withinss;within_ss_4
within_ss_5 = km_cluster_5$tot.withinss;within_ss_5
within_ss_6 = km_cluster_6$tot.withinss;within_ss_6
within_ss_7 = km_cluster_7$tot.withinss;within_ss_7
within_ss_8 = km_cluster_8$tot.withinss;within_ss_8
within_ss_9 = km_cluster_9$tot.withinss;within_ss_9
within_ss_10 = km_cluster_10$tot.withinss;within_ss_10
within_ss_11 = km_cluster_11$tot.withinss;within_ss_11
within_ss_12 = km_cluster_12$tot.withinss;within_ss_12
within_ss_13 = km_cluster_13$tot.withinss;within_ss_13
within_ss_14 = km_cluster_14$tot.withinss;within_ss_14
within_ss_15 = km_cluster_15$tot.withinss;within_ss_15
within_ss_16 = km_cluster_16$tot.withinss;within_ss_16
within_ss_17 = km_cluster_17$tot.withinss;within_ss_17
within_ss_18 = km_cluster_18$tot.withinss;within_ss_18
within_ss_19 = km_cluster_19$tot.withinss;within_ss_19
within_ss_20 = km_cluster_20$tot.withinss;within_ss_20
within_ss_21 = km_cluster_21$tot.withinss;within_ss_21
within_ss_22 = km_cluster_22$tot.withinss;within_ss_22
within_ss_23 = km_cluster_23$tot.withinss;within_ss_23
within_ss_24 = km_cluster_24$tot.withinss;within_ss_24
within_ss_25 = km_cluster_25$tot.withinss;within_ss_25
within_ss_26 = km_cluster_26$tot.withinss;within_ss_26
within_ss_27 = km_cluster_27$tot.withinss;within_ss_27
within_ss_28 = km_cluster_28$tot.withinss;within_ss_28

within_ss = c(within_ss_1,within_ss_2,within_ss_3,within_ss_4,within_ss_5,within_ss_6,within_ss_7,within_ss_8,within_ss_9,within_ss_10,within_ss_11,within_ss_12,within_ss_13,within_ss_14,within_ss_15,within_ss_16,within_ss_17,within_ss_18,within_ss_19,within_ss_20,within_ss_21,within_ss_22,within_ss_23,within_ss_24,within_ss_25,within_ss_26,within_ss_27,within_ss_28)

within_ss
library(ggplot2)
ggplot(data=data.frame(cluster = 1:28,within_ss),aes(x=cluster,y=within_ss))+
  geom_line(col='steelblue',size=1.2)+
  geom_point()+
  scale_x_continuous(breaks=seq(1,28,1))
```
```{r}
set.seed(1706)
# choose 16 clusters based on previous visulization
km = kmeans(x = pca_df,centers = 16,iter.max=10000,nstart=25)
k_segments = km$cluster
table(k_segments)
```
```{r}
```
```{r}
#import customer data
customers_clean= read.csv('customers_clean.csv')
```
```{r}
#apply pca on customer data
pca_customer = predict(pca_facto, newdata = customers_clean)
pca_cus = pca_customer$coord
```
```{r}
#apply kmeans clusters on customer data
centers = km$centers
closest.cluster <- function(x) {
  cluster.dist <- apply(centers, 1, function(y) sqrt(sum((x-y)^2)))
  return(which.min(cluster.dist)[1])
}
clusters_cus <- apply(pca_cus, 1, closest.cluster)
clusters_cus

clusters_az <- apply(pca_df, 1, closest.cluster)
clusters_az

```
```{r}
#customer distribution
dist_cus = data.frame(table(clusters_cus)/nrow(customers_impute)*100)
colnames(dist_cus)=c('cluster','freq')
dist_cus
```
```{r}
ggplot(dist_cus,aes(cluster,freq))+
  geom_bar(stat = 'identity')
```
```{r}
#general population distribution
dist_az = data.frame(table(clusters_az)/nrow(azdias1_impute)*100)
colnames(dist_az)=c('cluster','freq')
dist_az
```
```{r}
library(ggplot2)
ggplot(distr_az,aes(cluster,freq))+
  geom_bar(stat = 'identity')
```
```{r}
#compare distribution
compare = data.frame(cluster=dist_az$cluster, freq_az=dist_az$freq,freq_customer=dist_cus$freq)
compare
```
```{r}
#target group
target = azdias1_impute[clusters_az==2,]
nrow(target)
#outside group
outside = azdias1_impute[clusters_az==5,]
nrow(outside)
```
```{r}
#comparison
plot_comparison = function(col_name){
  plot1 = ggplot(outside,aes_string(x=col_name))+geom_bar()+ggtitle('outside population distribution')
  plot2 = ggplot(azdias1_impute,aes_string(x=col_name))+geom_bar()+ggtitle('general population distribution')
  plot3 = ggplot(target,aes_string(x=col_name))+geom_bar()+ggtitle('target population distribution')
  print(plot1)
  print(plot2)
  print(plot3)
}
```
```{r}
plot_comparison('LP_STATUS_GROB_1') 
#customer group tend to be nostly top earners
```
```{r}
plot_comparison('FINANZ_MINIMALIST')#not interested in low financial interest
```
```{r}
plot_comparison('ANREDE_KZ')#tend to be male
```
```{r}
plot_comparison('HH_EINKOMMEN_SCORE')# our target group tend to be higer income household.
```
```{r}
plot_comparison('HH_EINKOMMEN_SCORE')# highest income households has the highest penertration. customers almost evenly comes from different income households. highest income households is the biggest part.
```
```{r}
#try different clusters
k_segments_7 = km_cluster_7$cluster
table(k_segments_7)
```
```{r}
centers_7 = km_cluster_7$centers
closest.cluster <- function(x) {
  cluster.dist <- apply(centers_7, 1, function(y) sqrt(sum((x-y)^2)))
  return(which.min(cluster.dist)[1])
}
clusters_7_cus <- apply(pca_cus, 1, closest.cluster)
clusters_7_cus

clusters_7_az <- apply(pca_df, 1, closest.cluster)
clusters_7_az

```
```{r}
#customer distribution
dist_cus_7 = data.frame(table(clusters_7_cus)/nrow(customers_impute)*100)
colnames(dist_cus_7)=c('cluster','freq')
dist_cus_7
```
```{r}
ggplot(dist_cus_7,aes(cluster,freq))+
  geom_bar(stat = 'identity')
```
```{r}
#general population distribution
dist_az_7 = data.frame(table(clusters_7_az)/nrow(azdias1_impute)*100)
colnames(dist_az_7)=c('cluster','freq')
dist_az_7
```
```{r}
library(ggplot2)
ggplot(dist_az_7,aes(cluster,freq))+
  geom_bar(stat = 'identity')
```
```{r}
#compare distribution
compare_7 = data.frame(cluster=dist_az_7$cluster, freq_az=dist_az_7$freq,freq_customer=dist_cus_7$freq)
compare_7
```
```{r}
#target group
target_7 = azdias1_impute[clusters_7_az==6,]
nrow(target_7)
#outside group
outside_7 = azdias1_impute[clusters_7_az==7,]
nrow(outside_7)
```
```{r}
#comparison
plot_comparison_7 = function(col_name){
  plot1 = ggplot(outside_7,aes_string(x=col_name))+geom_bar()+ggtitle('outside population distribution')
  plot2 = ggplot(azdias1_impute,aes_string(x=col_name))+geom_bar()+ggtitle('general population distribution')
  plot3 = ggplot(target_7,aes_string(x=col_name))+geom_bar()+ggtitle('target population distribution')
  print(plot1)
  print(plot2)
  print(plot3)
}
```
```{r}
plot_comparison_7('LP_STATUS_GROB_1') 
#customer group tend to be nostly top earners
```
```{r}
plot_comparison_7('FINANZ_MINIMALIST')#not interested in low financial interest
```
```{r}
plot_comparison_7('ANREDE_KZ')#tend to be male
```
```{r}
plot_comparison_7('HH_EINKOMMEN_SCORE')# our target group tend to be higer income household.
```
```{r}
plot_comparison_7('HH_EINKOMMEN_SCORE')# higher income households are our target.
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```